# Generated by Django 4.1.3 on 2022-11-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_phone_alter_member_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
